import { StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const C = {
  bg: '#181818',
  surface: '#1d1d1d',
  surfaceActive: '#2a282a',
  border: '#383838',
  borderActive: '#163761',
  text: '#d6d6dd',
  muted: '#7a797a',
  accent: '#228df2',
  danger: '#f14c4c',
  success: '#15ac91',
  warning: '#ea7620',
};

export const workspaceStyles = StyleSheet.create({
  screen: { backgroundColor: C.bg, flex: 1 },
  topSafe: { backgroundColor: C.surface, borderBottomColor: C.border, borderBottomWidth: 1 },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  topBarLeft: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 8, minWidth: 0 },
  topBarTitle: {
    color: '#d1d1d1',
    flex: 1,
    fontFamily: Fonts.sans,
    fontSize: 12,
    fontWeight: '400',
  },
  topBarRight: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  iconBtn: {
    alignItems: 'center',
    borderRadius: 6,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  scroll: { flex: 1 },
  scrollContent: { gap: 16, paddingBottom: 40, paddingTop: 12 },
  section: { gap: 1 },
  sectionLabel: {
    color: C.muted,
    fontFamily: Fonts.sans,
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 0.8,
    marginBottom: 4,
    paddingHorizontal: 16,
  },
  emptyRow: { paddingHorizontal: 16, paddingVertical: 8 },
  emptyText: { color: C.muted, fontFamily: Fonts.sans, fontSize: 12 },
  deviceRow: {
    backgroundColor: C.surface,
    borderBottomColor: C.border,
    borderBottomWidth: 1,
    borderTopColor: C.border,
    borderTopWidth: 1,
    gap: 8,
    marginBottom: -1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  deviceRowActive: {
    backgroundColor: C.surfaceActive,
    borderBottomColor: C.borderActive,
    borderTopColor: C.borderActive,
  },
  deviceMain: { gap: 3 },
  deviceTopRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  deviceName: {
    color: '#d1d1d1',
    flex: 1,
    fontFamily: Fonts.sans,
    fontSize: 13,
    fontWeight: '500',
  },
  deviceMeta: { color: C.muted, fontFamily: Fonts.sans, fontSize: 11 },
  deviceState: {
    fontFamily: Fonts.sans,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  deviceUrl: { color: C.muted, fontFamily: Fonts.mono, fontSize: 11, paddingLeft: 14 },
  deviceActions: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingLeft: 14 },
  actionChip: {
    backgroundColor: C.bg,
    borderColor: C.border,
    borderRadius: 4,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  actionChipText: { color: C.accent, fontFamily: Fonts.sans, fontSize: 11, fontWeight: '500' },
  forgetText: {
    color: C.muted,
    fontFamily: Fonts.sans,
    fontSize: 11,
    textDecorationLine: 'underline',
  },
  fileRow: {
    alignItems: 'center',
    backgroundColor: C.surface,
    borderBottomColor: C.border,
    borderBottomWidth: 1,
    borderTopColor: C.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: -1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minHeight: 44,
  },
  rowDisabled: { opacity: 0.4 },
  fileIcon: { color: C.muted, fontSize: 13, width: 16 },
  fileInfo: { flex: 1, gap: 2 },
  fileName: { color: '#d1d1d1', fontFamily: Fonts.sans, fontSize: 13, fontWeight: '400' },
  filePath: { color: C.muted, fontFamily: Fonts.mono, fontSize: 11 },
  chevron: { color: C.muted, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '400' },
  errorBar: {
    backgroundColor: 'rgba(241,76,76,0.08)',
    borderColor: 'rgba(241,76,76,0.25)',
    borderRadius: 4,
    borderWidth: 1,
    marginHorizontal: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  errorText: { color: C.danger, fontFamily: Fonts.sans, fontSize: 12 },
});
